<#
  sync-classes.ps1
  Reads class-deadlines.md and rewrites the CLASS-SYNC block inside planner.md's
  "## Scheduled" section. Idempotent: re-run any time. Your own hand-written
  scheduled items live outside the markers and are never touched.

  Usage:  powershell -ExecutionPolicy Bypass -File sync-classes.ps1
          -WhatIf   show what would change without writing
#>
[CmdletBinding(SupportsShouldProcess)]
param()

$Root        = Split-Path -Parent $MyInvocation.MyCommand.Path
$SourcePath  = Join-Path $Root 'class-deadlines.md'
$PlannerPath = Join-Path $Root 'planner.md'
$Start       = '<!-- CLASS-SYNC:START - generated by sync-classes.ps1, do not edit by hand -->'
$End         = '<!-- CLASS-SYNC:END -->'

if (-not (Test-Path $SourcePath))  { throw "Missing $SourcePath" }
if (-not (Test-Path $PlannerPath)) { throw "Missing $PlannerPath" }

# ---- parse the deadline source ----
$items = @()
foreach ($raw in (Get-Content $SourcePath -Encoding UTF8)) {
  $t = $raw.Trim()
  if ($t -eq '' -or $t.StartsWith('#')) { continue }
  if ($t -notmatch '^(\d{4}-\d{2}-\d{2})\s*\|\s*([0-9:]*)\s*\|\s*([^|]+?)\s*\|\s*(.+)$') { continue }
  $date = $Matches[1]; $time = $Matches[2].Trim(); $class = $Matches[3].Trim(); $what = $Matches[4].Trim()
  $items += [pscustomobject]@{
    Date = $date
    Sort = "$date " + $(if ($time) { $time.PadLeft(5,'0') } else { '99:99' })
    Line = "- $date " + $(if ($time) { "$time " } else { '' }) + "${class}: $what"
  }
}
if (-not $items.Count) { throw "No deadline lines parsed from $SourcePath - check the format." }
$items = $items | Sort-Object Sort

$block = @($Start) + ($items | ForEach-Object { $_.Line }) + @($End)

# ---- splice into planner.md ----
$lines   = @(Get-Content $PlannerPath -Encoding UTF8)
$sIdx    = [array]::IndexOf($lines, $Start)
$eIdx    = [array]::IndexOf($lines, $End)

if ($sIdx -ge 0 -and $eIdx -gt $sIdx) {
  # replace existing block in place
  $out = @()
  if ($sIdx -gt 0) { $out += $lines[0..($sIdx-1)] }
  $out += $block
  if ($eIdx -lt $lines.Count-1) { $out += $lines[($eIdx+1)..($lines.Count-1)] }
  $action = "replaced existing block"
} else {
  # first run: append the block at the end of the "## Scheduled" section
  $schedIdx = -1
  for ($i=0; $i -lt $lines.Count; $i++) { if ($lines[$i] -match '^\s*##\s*Scheduled\s*$') { $schedIdx = $i; break } }
  if ($schedIdx -lt 0) { throw "No '## Scheduled' heading found in planner.md" }
  $nextIdx = $lines.Count
  for ($i=$schedIdx+1; $i -lt $lines.Count; $i++) { if ($lines[$i] -match '^\s*##\s+') { $nextIdx = $i; break } }
  # back off trailing blank lines so the block sits tight under the user's own entries
  $insertAt = $nextIdx
  while ($insertAt -gt $schedIdx+1 -and $lines[$insertAt-1].Trim() -eq '') { $insertAt-- }

  $out  = @($lines[0..($insertAt-1)])
  $out += $block
  $out += @('')
  if ($insertAt -lt $lines.Count) { $out += $lines[$insertAt..($lines.Count-1)] }
  $action = "inserted new block into '## Scheduled'"
}

if ($PSCmdlet.ShouldProcess($PlannerPath, "write $($items.Count) class deadlines ($action)")) {
  $enc = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllLines($PlannerPath, $out, $enc)
  Write-Host "Synced $($items.Count) class deadlines into planner.md ($action)."
  $next = $items | Where-Object { [datetime]$_.Date -ge (Get-Date).Date } | Select-Object -First 5
  if ($next) { Write-Host "`nNext up:"; $next | ForEach-Object { Write-Host "  $($_.Line.Substring(2))" } }
} else {
  Write-Host "[WhatIf] would $action with $($items.Count) items."
}
